In [1]:
import pandas as pd
import numpy as np

direc = 'C:/Users/54115/Documents/Ramiro/Taller/'

In [2]:
inst = 'tesla'

exp = ['sma','ema', 'boll', 'rsi', 'macd']

In [3]:
def read_exp(exp, df):
    if exp == 'sma':
        df['Strategy'] = 'SMA(' + df['short_sma'].astype(str) + ',' + df['long_sma'].astype(str) + ')'
        df = df[['Strategy', 'pnl', 'port_max_dd']]
        
    if exp == 'ema':
        df['Strategy'] = 'EMA(' + df['short_ema'].astype(str) + ',' + df['long_ema'].astype(str) + ')'
        df = df[['Strategy', 'pnl', 'port_max_dd']]
        
    if exp == 'boll':
        df['Strategy'] = 'BOLL(' + df['ma'].astype(str) + ',' + df['stdev'].astype(str) + ')'
        df = df[['Strategy', 'pnl', 'port_max_dd']]
        
    if exp == 'rsi':
        df['Strategy'] = 'RSI(' + df['periods'].astype(str) + ',' + df['oversold'].astype(str) + ',' + df['overbought'].astype(str) +')'
        df = df[['Strategy', 'pnl', 'port_max_dd']]
        
    if exp == 'macd':
        df['Strategy'] = 'MACD(' + df['short_ema'].astype(str) + ',' + df['long_ema'].astype(str) + ',' + df['signal'].astype(str) +')'
        df = df[['Strategy', 'pnl', 'port_max_dd']]
        
    return df

In [4]:
def transform_exp(inst):
    result_df = pd.DataFrame()
    
    for i in range (0,5):
        df = pd.read_excel(direc + 'experiment_' + exp[i] + '_' + inst + '.xlsx')
        df = read_exp(exp[i], df)
        
        result_df = result_df.append(df)
        
    result_df.reset_index(inplace = True, drop = True)
    result_df.sort_values(by='pnl', ascending = False, inplace = True)
    
    name_col = 'pnl_' + inst
    result_df.rename(columns={"pnl": name_col}, inplace = True)
    
    result_df.to_excel('C:/Users/54115/Documents/Ramiro/Taller/result' + inst + '.xlsx', index = False)
        
    return result_df

In [5]:
transform_exp(inst)

C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)

           Strategy  pnl_tesla  port_max_dd
2808  RSI(12,38,60)   3.960313    -0.051248
2809  RSI(13,35,64)   3.938327    -0.051248
2810  RSI(15,37,60)   3.898120    -0.063501
2811  RSI(12,37,60)   3.773855    -0.078882
2812  RSI(13,36,64)   3.750162    -0.051248
...             ...        ...          ...
7648  RSI(14,17,64)   0.000613    -0.265462
7649   RSI(7,19,63)   0.000411    -0.285334
7650   RSI(7,27,75)   0.000320    -0.308544
404      SMA(38,78)   0.000230    -0.299413
405      SMA(22,61)   0.000041    -0.340265

[8925 rows x 3 columns]

In [6]:
final_result = transform_exp('all').merge(transform_exp('microstrategy'), left_on = 'Strategy', right_on= 'Strategy')
final_result = final_result.merge(transform_exp('tesla'), left_on = 'Strategy', right_on= 'Strategy')
final_result = final_result.merge(transform_exp('salvador'), left_on = 'Strategy', right_on= 'Strategy')

final_result.sort_values(by=['pnl_all', 'pnl_microstrategy', 'pnl_tesla', 'pnl_salvador'], ascending = False, inplace = True)

final_result = final_result[['Strategy', 'pnl_all', 'pnl_microstrategy', 'pnl_tesla', 'pnl_salvador']]

final_result.to_excel('C:/Users/54115/Documents/Ramiro/Taller/final_result.xlsx', index = False)

final_result

C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3194979673.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append(df)
C:\Users\54115\AppData\Local\Temp\ipykernel_10856\3518147239.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'port_max_dd_x'} in the result is deprecated and will raise a MergeError in a future version.
  final_result = final_result.merge(transform_exp('salvador'), left_on = 'Strategy', right_on= 'Strategy')

           Strategy    pnl_all  pnl_microstrategy  pnl_tesla  pnl_salvador
0      RSI(6,36,70)  15.941050           4.197894   1.985984      0.169817
1      RSI(6,36,69)  14.737339           3.727784   1.715924      0.064016
2      RSI(6,36,68)  11.348527           2.898654   1.239622      0.029152
3      RSI(6,27,70)  10.310974           2.906839   1.576788      0.223588
4      RSI(6,27,69)   9.552296           2.568714   1.353775      0.117691
...             ...        ...                ...        ...           ...
3179  RSI(24,21,60)   0.005680           0.053333   0.053333      0.053333
3180  RSI(24,21,61)   0.005680           0.053333   0.053333      0.053333
3181  RSI(19,16,69)   0.004348           0.103128   0.103128      0.103128
3182  RSI(24,21,63)   0.003377           0.168859   0.168859      0.168859
3183  RSI(14,17,71)   0.000242           0.150987   0.150987      0.023958

[3184 rows x 5 columns]